version: '3.8'

services:

  web:
    build: ./project
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./project
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
      - ./downloads:/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MINIO_URL=storage:9000
      - MINIO_ACCESS_KEY=K5Uj7tTYNX2zdyPU
      - MINIO_SECRET_KEY=BBFufL13fafNSWL9L6oNugkWghNUQzSs
      - MINIO_BUCKET_VIDEO=video
      - REDDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - storage

  redis:
    image: redis:7
    volumes:
      - ./db:/data
    command: redis-server --save 60 1 --loglevel warning
 
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=password
    ports:
      - 8081:8081
    depends_on:
      - redis

  dashboard:
    build: ./project
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
  
  storage:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minio99
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"